extends: 'eslint:recommended'
env:
  node: true
  mocha: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    implidedStrict: true
    blockBindings: true
    arrowFunctions: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
rules:
  arrow-parens: [2, 'as-needed']
  arrow-spacing: 2
  semi: 2
  no-var: 2
  no-shadow: 1
  prefer-const: 1
  prefer-template: 2
  template-curly-spacing: [2, 'never']
  prefer-arrow-callback: 2
  object-shorthand: 2
  padded-blocks: 0
  func-names: 1
  one-var: 0
  eqeqeq: 2
  array-callback-return: 2
  consistent-return: 2
  no-else-return: 2
  no-empty-function: 1
  no-eval: 2
  no-eq-null: 2
  no-extend-native: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-new: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal: 2
  no-octal-escape: 2
  no-return-assign: 2
  no-process-env: 2
  no-proto: 2
  no-self-compare: 2
  no-throw-literal: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-void: 2
  no-with: 2
  radix: 2
  yoda: 2
  max-depth: [0, 4]
  max-params: [0, 3]
  max-statements: [0, 10]
  complexity: [0, 11]
